Repository cmu-delphi/www-main, pull requests merged in 2021-05, with the labels that each got.

#339 update to COVIDcast v2.4.0
  content/covidcast/release-log/headless/v2.4.0.md
  package-lock.json
  package.json
Labels: enhancement

#345 use published covidcast package
  .github/workflows/blog.yaml
  dependencies.R
Labels: chore

#352 Add two more survey publications
  content/covidcast/surveys.md
Labels: content

#356 Add contact form link
  config.toml
  themes/delphi/layouts/partials/footer.html
Labels: content

#358 docs: update README with more guides
  README.md
Labels: documentation

#360 update to EPIVis v2.0.0
  package-lock.json
  package.json
Labels: feat
