Repository cmu-delphi/www-main, pull requests merged in 2021-03, with the labels that each got.

#273 update dependencies
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: chore

#274 fix: move forecast eval to covidcast menu
  config.toml
  themes/delphi/layouts/partials/footer.html
Labels: enhancement

#282 feat: update to covidcast v2.1.0
  content/covidcast/release-log/headless/v2.1.0.md
  package-lock.json
  package.json
Labels: enhancement

#285 ci(fix): build images on main push
  .github/workflows/ci.yaml
Labels: chore

#289 prepare indicator-status page
  config.toml
  content/covidcast/indicator-status.md
Labels: enhancement

#288 feat: add template hero thumb image
  content/blog/2015-07-23-template-post.Rmd
  content/blog/2015-07-23-template-post.html
  static/blog/images/blog-thumb.jpg
  static/blog/images/blog-thumb.webp
  themes/delphi/assets/images/blog-thumb.xcf
Labels: chore

#287 tune landing page
  static/images/landing-page/API-image.jpg
  themes/delphi/assets/css/pages/_landing.scss
  themes/delphi/layouts/landing.html
  themes/delphi/layouts/partials/landing/latest-card.html
  themes/delphi/layouts/partials/landing/latest-news.html
Labels: design

#294 Add two more survey publications
  content/covidcast/surveys.md
Labels: content

#295 build: temporary disable blog post part
  .github/workflows/blog.yaml
  content/blog/2015-07-23-template-post.html
  content/blog/2020-08-28-api.Rmd
Labels: chore

#296 ci: add new release notes section
  .github/release-drafter.yml
Labels: chore

#297 update release process docs
  README.md
Labels: documentation

#256 C2B Post for review
  .gitignore
  content/blog/2021-03-10_c2b.Rmd
  content/blog/2021-03-10_c2b.html
  content/blog/c2b/C2B_output.csv
  content/blog/c2b/hosp_util.csv
  content/blog/c2b/test_and_hosp.csv
  content/blog/c2b/uncensored_HHS.csv
  content/people/index.md
  environment.yml
  static/blog/2021-03-10_c2b_files/figure-html/C2B-1.svg
  static/blog/2021-03-10_c2b_files/figure-html/HHS-1.svg
  static/blog/2021-03-10_c2b_files/figure-html/WPRDC-1.svg
  static/blog/2021-03-10_c2b_files/figure-html/rates-1.svg
  static/blog/images/blog-lg-c2b.jpg
  static/blog/images/blog-lg-c2b.webp
  static/blog/images/blog-thumb-c2b-1.jpg
  static/blog/images/blog-thumb-c2b-1.webp
  themes/delphi/assets/css/pages/_blog.scss
Labels: blog

#298 feat: update to COVIDcast v2.2.0
  config.toml
  package-lock.json
  package.json
  themes/delphi/assets/css/layout/_header_footer.scss
Labels: enhancement
