Repository cmu-delphi/www-main, pull requests merged in 2021-07, with the labels that each got.

#399 build: update dependencies
  package-lock.json
  package.json
  themes/delphi/layouts/_default/baseof.html
  themes/delphi/layouts/_default/coe.html
  themes/delphi/layouts/_default/team.html
  themes/delphi/layouts/_internal/pagination.html
  themes/delphi/layouts/blog/single.html
  themes/delphi/layouts/partials/about/collaborators.html
  themes/delphi/layouts/partials/blog/license.html
  themes/delphi/layouts/partials/font-awesome.html
  themes/delphi/layouts/partials/head/meta.html
  themes/delphi/layouts/partials/head/socialmedia.html
  themes/delphi/layouts/partials/landing/carousel.html
  themes/delphi/layouts/partials/landing/latest-news.html
  themes/delphi/layouts/partials/nav.html
  themes/delphi/layouts/partials/scripts.html
  themes/delphi/layouts/shortcodes/bibliography.html
  themes/delphi/layouts/shortcodes/systems.html
  themes/delphi/layouts/shortcodes/team.html
Labels: chore

#398 integrate www-covidcast-classic
  content/covidcast/classic.md
  package-lock.json
  package.json
  themes/delphi/assets/js/main.js
  themes/delphi/layouts/_default/covidcast_classic_app.html
  themes/delphi/layouts/partials/covidcast_classic/find-file.html
Labels: enhancement

#402 update to COVIDcast v2.5.3
  package-lock.json
  package.json
Labels: feat

#411 update to COVIDcast Classic v2.6.0
  package-lock.json
  package.json
Labels: feat

#414 update to COVIDcast v2.7.0
  package-lock.json
  package.json
Labels: feat

#415 ci: remove myself from release review
  .github/workflows/create_release.yml
  .github/workflows/release_main.yml
Labels: chore

#420 update to COVIDcast v2.7.1
  package-lock.json
  package.json
Labels: feat
