Repository cmu-delphi/www-main, pull requests merged in 2021-11, with the labels that each got.

#488 Update CTIS page
  content/covid19/ctis.md
Labels: content

#512 update to COVIDcast v2.8.1
  package-lock.json
  package.json
Labels: feat

#515 update dependencies
  .github/workflows/blog.yaml
  .github/workflows/ci.yaml
  .github/workflows/release_main.yml
  .gitignore
  package-lock.json
  package.json
Labels: chore
