Repository cmu-delphi/www-main, pull requests merged in 2021-06, with the labels that each got.

#372 fix: use new functions from package
  content/blog/2020-08-26-fb-survey.Rmd
  content/blog/2020-08-26-fb-survey.html
Labels: bug

#371 fix: improve webp conversion
  .vscode/settings.json
  README.md
  content/blog/2015-07-23-template-post.Rmd
  content/blog/2015-07-23-template-post.html
  content/blog/2021-03-10_c2b.Rmd
  content/blog/2021-03-10_c2b.html
  content/blog/images/blog-thumb-c2b-1.jpg
  content/blog/images/blog-thumb-img_A Syndromic COVID-19.jpg
  content/blog/images/blog-thumb-img_Accessing Open COVID-19.jpg
  content/blog/images/blog-thumb-img_New and Improved COVID.jpg
  content/blog/images/blog-thumb-img_facebook-survey-post.jpg
  content/blog/images/blog-thumb-img_google-survey-post.jpg
  content/blog/images/blog-thumb-img_hello-world.jpg
  content/blog/images/blog-thumb-vaccine-2.jpg
  content/blog/images/blog-thumb-vaccine-survey.jpg
  content/blog/images/blog-thumbnail_can symptoms surveys improve covid-19.jpg
  content/blog/images/causal-inference-mobility-thumb.jpg
  content/blog/images/holiday-gathering-small.jpg
  content/blog/images/masks-public-thumb.jpg
  content/blog/images/unpack-cfr-thumb.jpg
  package.json
  themes/delphi/layouts/blog/list.html
  themes/delphi/layouts/blog/single.html
  themes/delphi/layouts/partials/blog/card.html
  themes/delphi/layouts/partials/landing/latest-card.html
  themes/delphi/layouts/partials/landing/teampic.html
  themes/delphi/layouts/shortcodes/team.html
Labels: bug

#369 Create 2020_12_chng_partnership.md
  content/about/news/headless/2020_12_chng_partnership.md
Labels: content

#370 Create 2021_05_spaig_award.md
  content/about/news/headless/2021_05_12_spaig_award.md
Labels: content

#379 update to COVIDcast v2.5.0
  package-lock.json
  package.json
Labels: feat

#342 add Dashboard Builder page
  config.toml
  content/covidcast/dashboard.md
Labels: chore

#382 update to EPIVis v2.0.1
  package-lock.json
  package.json
Labels: enhancement

#386 update to COVIDcast v2.5.1
  package-lock.json
  package.json
Labels: feat

#390 update to COVIDcast v2.5.2
  package-lock.json
  package.json
Labels: feat
