Repository cmu-delphi/www-main, pull requests merged in 2022-01, with the labels that each got.

#549 Update careers page: Add Open Rank Faculty position
  content/about/careers/headless/2021_11_research_programmer_analyst.md
  content/about/careers/headless/2022_11_open_rank_faculty.md
  content/about/news/headless/2021_05_12_spaig_award.md
  content/about/news/headless/2021_11_22_nyt.md
  content/about/news/headless/2021_12_14_pnas.md
  content/about/news/images/2021-05-12-spaig-award-thumb.jpg
  content/about/news/images/2021-11-22-nyt-thumb.jpg
  content/about/news/images/2021-12-14-pnas-thumb.jpg
Labels: content

#557 update to COVIDcast v3.0.1
  package-lock.json
  package.json
Labels: feat

#561 Auto merge dev upon release
  .github/workflows/ci.yaml
  .github/workflows/release_main.yml
  README.md
Labels: chore

#562 Add hints about image sizes
  README.md
Labels: chore
